steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/visionmentor-backend', './backend']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/visionmentor-backend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'visionmentor-backend',
        '--image', 'gcr.io/$PROJECT_ID/visionmentor-backend',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/$PROJECT_ID/visionmentor-backend'